const DB_NAME='money-manager-premium',DB_VERSION=1,STORE='state';
const COLORS=['#2D6A4F','#40916C','#52B788','#74C69D','#1B4332','#3A86FF','#F4A261','#E76F51','#9D4EDD','#E63946','#0077B6','#B08968'];
const $=s=>document.querySelector(s); const page=document.body.dataset.page;
const money=n=>{const v=Math.round((Number(n)||0)*100)/100;return v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>{try{if(window.crypto&&crypto.randomUUID)return crypto.randomUUID()}catch{}return Math.random().toString(36).slice(2,10)+Date.now().toString(36)};
const monthLabelNow=()=>new Date().toLocaleDateString(undefined,{month:'long',year:'numeric'});
let state=null;
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function load(){try{const d=await openDB();return await new Promise((res,rej)=>{const q=d.transaction(STORE).objectStore(STORE).get('app');q.onsuccess=()=>res(q.result||{budget:null,history:[]});q.onerror=()=>rej(q.error)})}catch{try{return JSON.parse(localStorage.getItem('money-manager-state')||'{"budget":null,"history":[]}')}catch{return {budget:null,history:[]}}}}
async function save(s){try{const d=await openDB();await new Promise((res,rej)=>{const q=d.transaction(STORE,'readwrite').objectStore(STORE).put(s,'app');q.onsuccess=res;q.onerror=()=>rej(q.error)})}catch{localStorage.setItem('money-manager-state',JSON.stringify(s))}}
async function update(fn){const s=await load();fn(s);await save(s);state=s;return s}
function go(path){location.href=path}
function toast(msg){let x=$('#toast');if(!x){x=document.createElement('div');x.id='toast';x.className='toast';document.body.appendChild(x)}x.textContent=msg;x.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.style.display='none',1800)}
function totals(b){const a=b?.types?.reduce((s,t)=>s+Number(t.allocated||0),0)||0,p=b?.types?.reduce((s,t)=>s+Number(t.spent||0),0)||0;return{allocated:a,spent:p,remaining:a-p,pct:a?Math.min(100,p/a*100):0}}
function fmtDate(d){return new Date(d).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
function initSetup(s){if(s.setupRows===undefined){const prev=s.history?.[0];s.setupName=monthLabelNow();s.setupRows=prev?.types?.length?prev.types.map(t=>({name:t.name,allocated:String(t.allocated),color:t.color})):[{name:'Petrol',allocated:'',color:COLORS[6]},{name:'Outside Food',allocated:'',color:COLORS[7]},{name:'House Expense',allocated:'',color:COLORS[0]}]}}
function render(){const app=$('#app');if(!state){app.innerHTML='<div class="loading-wrap"><div class="spinner"></div></div>';return}if(!state.budget&&page!=='setup'){go('setup.html');return}let html=page==='setup'?renderSetup():page==='history'?renderHistory():page==='category'?renderCategory():renderDashboard();app.innerHTML='<div class="fade">'+html+'</div>';bindEvents()}
function renderDashboard(){const b=state.budget,t=totals(b);return `<div class="header"><div><div class="header-sub">Current budget</div><div class="header-title">${esc(b.name)}</div></div><button class="icon-btn-light" data-action="history">📈</button></div><div class="summary-card"><div class="summary-row"><div class="summary-stat"><div class="lbl">Total</div><div class="val">$${money(t.allocated)}</div></div><div class="divider"></div><div class="summary-stat"><div class="lbl">Spent</div><div class="val" style="color:var(--orange)">$${money(t.spent)}</div></div><div class="divider"></div><div class="summary-stat"><div class="lbl">Remaining</div><div class="val" style="color:${t.remaining<0?'var(--red)':'var(--green)'}">$${money(t.remaining)}</div></div></div><div class="progress-track"><div class="progress-fill" style="width:${t.pct}%;background:${t.remaining<0?'var(--red)':'var(--green)'}"></div></div></div><div class="cats-header"><div class="cats-title">Categories</div><button class="small-ghost-btn" data-action="openAddType">+ Add</button></div><div class="type-list">${b.types.length?b.types.map(cat=>`<div class="type-card" data-action="openType" data-id="${cat.id}"><div class="type-stripe" style="background:${cat.color}"></div><div class="type-body"><div class="type-top"><div class="type-name">${esc(cat.name)}</div><div class="type-actions"><button class="icon-btn-sm" style="background:${cat.color}1A" data-action="quickAdd" data-id="${cat.id}">+</button><span style="color:#B7C4BC">›</span></div></div><div class="type-nums"><span style="color:${cat.spent>cat.allocated?'var(--red)':'var(--muted)'}">$${money(cat.spent)} of $${money(cat.allocated)}</span><span style="font-weight:600;color:${cat.spent>cat.allocated?'var(--red)':'var(--green)'}">$${money(cat.allocated-cat.spent)} left</span></div><div class="progress-track-sm"><div class="progress-fill-sm" style="width:${cat.allocated?Math.min(100,cat.spent/cat.allocated*100):0}%;background:${cat.spent>cat.allocated?'var(--red)':cat.color}"></div></div></div></div>`).join(''):'<div class="empty-box">No categories yet. Add one to start tracking.</div>'}</div><div style="padding:16px"><button class="end-btn" data-action="confirmEnd">🏁 End month &amp; start new</button></div>`}
function renderCategory(){const id=new URLSearchParams(location.search).get('id'),t=state.budget?.types.find(x=>x.id===id);if(!t)return '<div class="section"><button class="secondary-btn" data-action="dashboard">← Dashboard</button></div>';const rem=t.allocated-t.spent,pct=t.allocated?Math.min(100,t.spent/t.allocated*100):0;return `<div class="header" style="background:${t.color}"><button class="icon-btn-light" data-action="dashboard">←</button><div class="header-title">${esc(t.name)}</div><button class="icon-btn-light" data-action="editType" data-id="${t.id}">🎨</button></div><div class="summary-card"><div class="summary-row"><div class="summary-stat"><div class="lbl">Allocated</div><div class="val">$${money(t.allocated)}</div></div><div class="divider"></div><div class="summary-stat"><div class="lbl">Spent</div><div class="val" style="color:var(--orange)">$${money(t.spent)}</div></div><div class="divider"></div><div class="summary-stat"><div class="lbl">Remaining</div><div class="val" style="color:${rem<0?'var(--red)':t.color}">$${money(rem)}</div></div></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%;background:${rem<0?'var(--red)':t.color}"></div></div></div><div style="padding:16px 16px 8px"><button class="primary-btn" style="background:${t.color}" data-action="addExpense" data-id="${t.id}">+ Add expense</button></div><div style="padding:8px 16px;font-weight:700;font-size:14.5px">Expense history</div><div style="padding:0 16px 24px;display:flex;flex-direction:column;gap:8px">${t.expenses.length?t.expenses.map(e=>`<div class="expense-row"><div><div style="font-weight:600;font-size:14px">$${money(e.amount)}</div><div style="font-size:12px;color:var(--muted2)">${e.note?esc(e.note)+' · ':''}${new Date(e.date).toLocaleDateString(undefined,{day:'numeric',month:'short'})}</div></div><button class="icon-btn-ghost" data-action="deleteExpense" data-type="${t.id}" data-exp="${e.id}">🗑</button></div>`).join(''):'<div class="empty-box">No expenses logged yet.</div>'}</div><div style="padding:0 16px 24px"><button class="danger-ghost-btn" data-action="confirmDelete" data-id="${t.id}">🗑 Delete category</button></div>`}
function renderHistory(){const total=state.history.reduce((s,h)=>s+Number(h.remaining||0),0);return `<div class="header"><button class="icon-btn-light" data-action="dashboard">←</button><div class="header-title">Savings history</div><div style="width:32px"></div></div><div class="summary-card" style="text-align:center"><div style="font-size:12px;color:var(--muted2)">Total carried across closed months</div><div style="font-size:24px;font-weight:700;color:${total<0?'var(--red)':'var(--green)'};margin-top:4px">$${money(total)}</div></div><div style="padding:16px;display:flex;flex-direction:column;gap:10px">${state.history.length?state.history.map(h=>`<div class="history-card"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><div style="font-weight:700;font-size:15px">${esc(h.name)}</div><div style="font-size:11.5px;color:var(--muted2)">Closed ${fmtDate(h.closedDate)}</div></div><div class="mini-stats"><div class="mini-stat"><div class="lbl">Total</div><div class="val">$${money(h.allocated)}</div></div><div class="mini-stat"><div class="lbl">Spent</div><div class="val" style="color:var(--orange)">$${money(h.spent)}</div></div><div class="mini-stat"><div class="lbl">Left</div><div class="val" style="color:${h.remaining<0?'var(--red)':'var(--green)'}">$${money(h.remaining)}</div></div></div><div style="display:flex;gap:5px;margin-top:10px;flex-wrap:wrap">${(h.types||[]).map(t=>`<span class="tag" style="background:${t.color}1A;color:${t.color}">${esc(t.name)}</span>`).join('')}</div></div>`).join(''):'<div class="empty-box">No closed budgets yet. End a month to see it here.</div>'}</div>`}
function renderSetup(){initSetup(state);const total=state.setupRows.reduce((s,r)=>s+(Number(r.allocated)||0),0),can=state.setupName.trim()&&state.setupRows.some(r=>r.name.trim()&&Number(r.allocated)>0);return `<div class="setup-hero"><div style="font-size:30px">💵</div><div style="font-size:20px;font-weight:700;color:#fff;margin-top:8px">${state.history.length?'Start a new month':'Set up your budget'}</div><div style="font-size:13px;color:#DFF3E7;margin-top:4px">${state.history.length?'Amounts carried over from last month — adjust as needed.':'Split your money into categories you can track.'}</div></div><div class="section"><label class="label">Budget name</label><input class="input" id="setup-name" value="${esc(state.setupName)}" placeholder="e.g. September 2026"></div><div class="section"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px"><label class="label" style="margin:0">Categories</label><span style="font-size:12px;color:var(--muted)">Total: $${money(total)}</span></div>${state.setupRows.map((r,i)=>`<div class="type-row"><button class="color-dot" style="background:${r.color}" data-action="cycleColor" data-idx="${i}"></button><input class="row-input" data-name="${i}" placeholder="Category name" value="${esc(r.name)}"><input class="row-input" style="text-align:right" data-amount="${i}" type="number" inputmode="decimal" placeholder="0" value="${esc(r.allocated)}"><button class="icon-btn-ghost" data-action="removeRow" data-idx="${i}">✕</button></div>`).join('')}<button class="add-row-btn" data-action="addRow">+ Add category</button></div><div style="padding:0 16px 24px"><button class="primary-btn" data-action="startBudget" ${can?'':'disabled'}>✓ Start budget</button></div>`}
function modal(html){document.body.insertAdjacentHTML('beforeend',html)}
function closeModal(){document.querySelector('.modal-overlay')?.remove()}
function expenseModal(id){const t=state.budget.types.find(x=>x.id===id);modal(`<div class="modal-overlay" data-overlay><div class="modal-sheet fade"><div class="modal-header"><div class="modal-title">Add expense · ${esc(t.name)}</div><button class="icon-btn-ghost" data-close>✕</button></div><label class="label">Amount</label><input class="input" id="exp-amount" type="number" min="0.01" step="0.01" inputmode="decimal" placeholder="0.00" autofocus><label class="label">Note (optional)</label><input class="input" id="exp-note" placeholder="e.g. Petrol pump refill"><button class="primary-btn" style="background:${t.color}" data-action="submitExpense" data-id="${id}">✓ Add</button></div></div>`)}
function editModal(id){const t=state.budget.types.find(x=>x.id===id);modal(`<div class="modal-overlay" data-overlay><div class="modal-sheet fade"><div class="modal-header"><div class="modal-title">Edit category</div><button class="icon-btn-ghost" data-close>✕</button></div><label class="label">Name</label><input class="input" id="edit-name" value="${esc(t.name)}"><label class="label">Allocated amount</label><input class="input" id="edit-allocated" type="number" min="0" step="0.01" value="${t.allocated}"><label class="label">Card color</label><div class="color-picker">${COLORS.map(c=>`<button class="swatch ${c===t.color?'selected':''}" style="background:${c}" data-pick-color="${c}"></button>`).join('')}</div><button class="primary-btn" data-action="saveType" data-id="${id}">✓ Save changes</button></div></div>`);window.__editColor=t.color}
function confirmModal(title,text,action,id){modal(`<div class="modal-overlay" data-overlay><div class="modal-sheet fade"><div class="modal-title" style="margin-bottom:8px">${title}</div><div style="font-size:13.5px;color:var(--muted);line-height:1.5;margin-bottom:20px">${text}</div><div style="display:flex;gap:10px"><button class="secondary-btn" style="flex:1" data-close>Cancel</button><button class="primary-btn" style="flex:1;margin-top:0" data-action="${action}" ${id?`data-id="${id}"`:''}>Confirm</button></div></div></div>`)}
function bindEvents(){document.onclick=async e=>{const target=e.target.closest('[data-action],[data-close]');if(!target)return;if(target.dataset.close!==undefined||target.dataset.overlay!==undefined){if(target===e.target||target.dataset.close!==undefined)closeModal();return}const a=target.dataset.action,id=target.dataset.id;
 if(a==='history')return go('history.html');if(a==='dashboard')return go('dashboard.html');if(a==='openType')return go('category.html?id='+encodeURIComponent(id));if(a==='quickAdd'||a==='addExpense')return expenseModal(id);if(a==='editType')return editModal(id);if(a==='confirmEnd'){const t=totals(state.budget);return confirmModal('End this month?',`This will lock “${esc(state.budget.name)}” into history with $${money(t.remaining)} remaining, and let you start a fresh budget.`,'endBudget')}
 if(a==='endBudget'){await update(s=>{const t=totals(s.budget);s.history.unshift({id:s.budget.id,name:s.budget.name,startDate:s.budget.startDate,closedDate:new Date().toISOString(),allocated:t.allocated,spent:t.spent,remaining:t.remaining,types:s.budget.types.map(x=>({name:x.name,color:x.color,allocated:x.allocated,spent:x.spent}))});s.budget=null;s.setupRows=undefined;s.setupName=monthLabelNow()});closeModal();return go('setup.html')}
 if(a==='confirmDelete')return confirmModal('Delete category?', 'This removes the category and all its expense history. This cannot be undone.','deleteType',id);
 if(a==='deleteType'){await update(s=>{s.budget.types=s.budget.types.filter(t=>t.id!==id)});closeModal();return go('dashboard.html')}
 if(a==='deleteExpense'){await update(s=>{const t=s.budget.types.find(x=>x.id===target.dataset.type),ex=t?.expenses.find(x=>x.id===target.dataset.exp);if(ex){t.spent=Math.max(0,Number(t.spent||0)-Number(ex.amount));t.expenses=t.expenses.filter(x=>x.id!==target.dataset.exp)}});return location.reload()}
 if(a==='submitExpense'){const amount=Number($('#exp-amount')?.value),note=$('#exp-note')?.value.trim()||'';if(!(amount>0))return toast('Enter a valid amount');await update(s=>{const t=s.budget.types.find(x=>x.id===id);t.spent=Number(t.spent||0)+amount;t.expenses=t.expenses||[];t.expenses.unshift({id:uid(),amount,note,date:new Date().toISOString()})});closeModal();return location.reload()}
 if(a==='saveType'){const name=$('#edit-name')?.value.trim(),allocated=Number($('#edit-allocated')?.value);if(!name||allocated<0)return toast('Check the category details');await update(s=>Object.assign(s.budget.types.find(x=>x.id===id),{name,allocated,color:window.__editColor||s.budget.types.find(x=>x.id===id).color}));closeModal();return location.reload()}
 if(a==='addRow'){state.setupRows.push({name:'',allocated:'',color:COLORS[state.setupRows.length%COLORS.length]});return render()}
 if(a==='removeRow'){state.setupRows.splice(Number(target.dataset.idx),1);return render()}
 if(a==='cycleColor'){const i=Number(target.dataset.idx),idx=COLORS.indexOf(state.setupRows[i].color);state.setupRows[i].color=COLORS[(idx+1)%COLORS.length];return render()}
 if(a==='startBudget'){const name=$('#setup-name')?.value.trim();state.setupName=name;const rows=state.setupRows.filter(r=>r.name.trim()&&Number(r.allocated)>0);if(!name||!rows.length)return toast('Add a name and at least one category');await update(s=>{s.budget={id:uid(),name,startDate:new Date().toISOString(),types:rows.map(r=>({id:uid(),name:r.name.trim(),color:r.color,allocated:Number(r.allocated),spent:0,expenses:[]}))};s.setupRows=undefined;s.setupName=name});return go('dashboard.html')}};
document.addEventListener('input',e=>{if(e.target.id==='setup-name'){state.setupName=e.target.value}if(e.target.dataset.name!==undefined){state.setupRows[+e.target.dataset.name].name=e.target.value}if(e.target.dataset.amount!==undefined){state.setupRows[+e.target.dataset.amount].allocated=e.target.value}});
document.addEventListener('change',e=>{if(e.target.dataset.amount!==undefined){state.setupRows[+e.target.dataset.amount].allocated=e.target.value}});
(async()=>{state=await load();if(!state.budget&&page!=='setup'){return go('setup.html')}render()})();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));
